# Generated by Django 4.2.2 on 2023-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DysonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название Дайсона')),
                ('image', models.ImageField(upload_to='')),
                ('articul', models.CharField(max_length=40, verbose_name='Артикул')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('country', models.CharField(max_length=10, verbose_name='Страна')),
                ('characteristic', models.TextField(max_length=200, verbose_name='Характеристика')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('cap', models.CharField(max_length=10, verbose_name='Количество насадок')),
                ('count', models.CharField(max_length=10, verbose_name='Количество в наличии')),
            ],
            options={
                'verbose_name': 'Таблица Дайсонов',
                'verbose_name_plural': 'Дайсон',
            },
        ),
    ]
