# Generated by Django 4.2.2 on 2023-07-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dysonmodel',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Название Дайсона'),
        ),
    ]
