# Generated by Django 4.2.2 on 2023-07-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dysonmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dysonmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
