# Generated by Django 4.2.2 on 2023-07-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_dysonmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dysonmodel',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
