# Generated by Django 4.2.2 on 2023-07-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dysonmodel_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDysonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(max_length=10, verbose_name='Заказаное количество')),
            ],
            options={
                'verbose_name': 'Товары заказов',
                'verbose_name_plural': 'Товар заказа',
            },
        ),
        migrations.AlterField(
            model_name='dysonmodel',
            name='cap',
            field=models.PositiveIntegerField(verbose_name='Количество насадок'),
        ),
        migrations.AlterField(
            model_name='dysonmodel',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество в наличии'),
        ),
        migrations.AlterField(
            model_name='dysonmodel',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('mail', models.EmailField(max_length=255, verbose_name='Емэйл клента')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер клиента')),
                ('finally_sum', models.PositiveIntegerField(verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('ВО', 'в обработке'), ('ОП', 'Оплачено'), ('ДС', 'Доставка'), ('ЗВ', 'Завершено')], max_length=255)),
                ('save_orders', models.ManyToManyField(to='main.orderdysonmodel')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.AddField(
            model_name='orderdysonmodel',
            name='dyson_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dysonmodel'),
        ),
    ]
